// Regenerates resources/project_structure/backend_structure.md
// Usage: node resources/project_structure/generate_dependency_graph.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '../..');
const SRC = path.resolve(ROOT, 'clean-architecture-visualizer/src');

const files = [];
function walk(d) {
  for (const f of fs.readdirSync(d)) {
    const p = path.join(d, f);
    const st = fs.statSync(p);
    if (st.isDirectory()) walk(p);
    else if (f.endsWith('.ts') && !f.endsWith('.test.ts')) files.push(p);
  }
}
walk(SRC);
files.sort();
const frag = (p) => p.replace(SRC + '/', '').replace(/\.ts$/, '');

const layers = {
  app: ['app'],
  entity: ['entity'],
  use_case: ['use_case'],
  interface_adapter: ['interface_adapter'],
  data_access: ['data_access'],
  server: ['server'],
  database: ['database'],
  types: ['types'],
};
function layerOf(p) {
  const seg = p.split('/');
  for (const [l, dirs] of Object.entries(layers))
    if (dirs.some((d) => seg.includes(d))) return l;
  return 'root';
}

const importRe = /import[\s\S]*?from\s+['"](\.[^'"]+)['"]/g;
const edges = [];
for (const f of files) {
  const txt = fs.readFileSync(f, 'utf8');
  const srcDir = path.dirname(f);
  let m;
  while ((m = importRe.exec(txt))) {
    const rel = m[1].replace(/\.(js|ts)$/, '');
    const target = path.resolve(srcDir, rel);
    let resolved = null;
    for (const cand of [target + '.ts', target + '.js', path.join(target, 'index.ts')])
      if (fs.existsSync(cand)) { resolved = cand; break; }
    if (resolved && resolved.startsWith(SRC)) edges.push([f, resolved]);
  }
}
const fileEdges = edges
  .map(([a, b]) => [frag(a), frag(b)])
  .sort((a, b) => a[0].localeCompare(b[0]) || a[1].localeCompare(b[1]));

// layer -> layer counts
const ll = {};
for (const [a, b] of edges) {
  const la = layerOf(a), lb = layerOf(b);
  if (la === lb) continue;
  const k = `${la}->${lb}`;
  ll[k] = (ll[k] || 0) + 1;
}

const layerOrder = ['entity', 'use_case', 'gateways', 'interface_adapter', 'data_access', 'database', 'server', 'app', 'types'];
const counts = {};
for (const f of files) { const l = layerOf(f); counts[l] = (counts[l] || 0) + 1; }

const md = [];
md.push('# CAVE Backend Structure & Dependency Map (auto-generated)');
md.push('');
md.push('> Generated by `generate_dependency_graph.mjs`. Regenerate with `node resources/project_structure/generate_dependency_graph.mjs`.');
md.push('> Dependency rule (RFC-0001): all imports point inward. `entity <- use_case <- interface_adapter <- data_access/server`.');
md.push('');
md.push('## Layer File Counts');
md.push('');
for (const l of Object.keys(counts).sort()) md.push(`- \`${l}/\` : ${counts[l]} files`);
md.push('');
md.push('## Compact File Tree (src/)');
md.push('');
md.push('```');
const dirs = [...new Set(files.map((f) => path.dirname(f)))].sort();
for (const d of dirs) {
  md.push(d.replace(SRC + '/', '') + '/');
  for (const f of files.filter((x) => path.dirname(x) === d).sort())
    md.push('  ' + path.basename(f).replace(/\.ts$/, ''));
}
md.push('```');
md.push('');
md.push('## Layer-to-Layer Dependencies (importing file counts)');
md.push('');
md.push('| from \\ to | entity | types | use_case | interface_adapter | data_access | database | server | app |');
md.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- |');
const cols = ['entity', 'types', 'use_case', 'interface_adapter', 'data_access', 'database', 'server', 'app'];
const rows = {};
for (const k of Object.keys(ll)) {
  const [a, b] = k.split('->');
  rows[a] = rows[a] || {};
  rows[a][b] = ll[k];
}
for (const from of cols) {
  const r = rows[from] || {};
  md.push(`| ${from} | ${cols.map((t) => r[t] ?? 0).join(' | ')} |`);
}
md.push('');
md.push('## File-Level Dependency Edges (imports)');
md.push('');
md.push('```');
for (const [a, b] of fileEdges) md.push(`${a} -> ${b}`);
md.push('```');
md.push('');

fs.writeFileSync(path.resolve(HERE, 'backend_structure.md'), md.join('\n'));
console.log('Wrote backend_structure.md (' + fileEdges.length + ' edges)');
